kdl_parser: switch from TinyXML to TinyXML2
ros/kdl_parser pull request #2
Opened 2017-06-14 12:14 UTC by rojkov

The library TinyXML is considered to be unmaintained and
since all future development is focused on TinyXML2 this
patch updates kdl_parser to use TinyXML2.

depends on https://github.com/ros/robot_model/pull/205

2017-06-14 16:28 UTC, sloretz requested changes
Thanks for the pull request @rojkov! This will have to wait until ROS M for the same reasons as ros/robot_model#205.

2017-06-14 16:28 UTC, sloretz commented on kdl_parser/include/kdl_parser/kdl_parser.hpp
> -bool treeFromXml(TiXmlDocument *xml_doc, KDL::Tree& tree);
This API can't be changed in the released ROS versions since it would break API/ABI compatibility.

2017-06-14 16:30 UTC, sloretz commented
CI likely failed to to tinyxml2 not being in the `package.xml`

2017-12-18 16:55 UTC, sloretz commented
@rojkov Would you mind targeting this at the `melodic-devel` branch instead?

2017-12-19 10:00 UTC, rojkov commented
Sure, resubmitted as https://github.com/ros/kdl_parser/pull/4

2018-02-01 19:25 UTC, clalancette commented
Since this is targeted at melodic in #4 now, closing this old one out.

2018-02-01 19:25 UTC, closed without merging