logging feature: fprintf replaced by rcutils_log
ros/kdl_parser pull request #52
Opened 2021-02-12 14:23 UTC by yuraSomatic

2021-02-12 16:45 UTC, clalancette requested changes
I've left a few review comments.  Also, this is failing CI because of some uncrustify and cpplint errors.  Please fix those as well.

2021-02-12 16:45 UTC, clalancette commented on kdl_parser/CMakeLists.txt
> +find_package(rcutils)
```suggestion
find_package(rcutils REQUIRED)
```

Also, please put this in alphabetical order in the list above.

2021-02-12 16:45 UTC, clalancette commented on kdl_parser/CMakeLists.txt
> +  rcutils)
Alphabetic order, please.

2021-02-12 16:45 UTC, clalancette commented on kdl_parser/src/kdl_parser.cpp
> +        rcutils_log(nullptr,
Can we instead use:

`RCUTILS_LOG_WARN_NAMED` here?

(same goes for all of the other uses below)

2022-06-17 13:18 UTC, SammyRamone commented
Is there any progress on this? Currently we get the following blob of spam each time we start our software due to the issue that is addressed in this PR.
The proposed changes seem to make sense. As @yuraSomatic did not further responde, could you (@clalancette) just do these changes and merge the PR? 

```
[robot_state_publisher-3] Link torso had 6 children
[robot_state_publisher-3] Link neck had 1 children
[robot_state_publisher-3] Link head had 3 children
[robot_state_publisher-3] Link camera had 0 children
[robot_state_publisher-3] Link camera_optical_frame had 0 children
[robot_state_publisher-3] Link imu_frame_2 had 0 children
[robot_state_publisher-3] Link l_hip_1 had 1 children
[robot_state_publisher-3] Link l_hip_2 had 1 children
[robot_state_publisher-3] Link l_upper_leg had 1 children
[robot_state_publisher-3] Link l_lower_leg had 1 children
[robot_state_publisher-3] Link l_ankle had 1 children
[robot_state_publisher-3] Link l_foot had 6 children
[robot_state_publisher-3] Link llb had 1 children
[robot_state_publisher-3] Link l_cleat_l_back had 0 children
[robot_state_publisher-3] Link llf had 1 children
[robot_state_publisher-3] Link l_cleat_l_front had 0 children
[robot_state_publisher-3] Link lrb had 1 children
[robot_state_publisher-3] Link l_cleat_r_back had 0 children
[robot_state_publisher-3] Link lrf had 1 children
[robot_state_publisher-3] Link l_cleat_r_front had 0 children
[robot_state_publisher-3] Link l_sole had 0 children
[robot_state_publisher-3] Link l_toe had 0 children
[robot_state_publisher-3] Link l_shoulder had 1 children
[robot_state_publisher-3] Link l_upper_arm had 1 children
[robot_state_publisher-3] Link l_lower_arm had 1 children
[robot_state_publisher-3] Link l_wrist had 0 children
[robot_state_publisher-3] Link r_hip_1 had 1 children
[robot_state_publisher-3] Link r_hip_2 had 1 children
[robot_state_publisher-3] Link r_upper_leg had 1 children
[robot_state_publisher-3] Link r_lower_leg had 1 children
[robot_state_publisher-3] Link r_ankle had 1 children
[robot_state_publisher-3] Link r_foot had 6 children
[robot_state_publisher-3] Link rlb had 1 children
[robot_state_publisher-3] Link r_cleat_l_back had 0 children
[robot_state_publisher-3] Link rlf had 1 children
[robot_state_publisher-3] Link r_cleat_l_front had 0 children
[robot_state_publisher-3] Link rrb had 1 children
[robot_state_publisher-3] Link r_cleat_r_back had 0 children
[robot_state_publisher-3] Link rrf had 1 children
[robot_state_publisher-3] Link r_cleat_r_front had 0 children
[robot_state_publisher-3] Link r_sole had 0 children
[robot_state_publisher-3] Link r_toe had 0 children
[robot_state_publisher-3] Link r_shoulder had 1 children
[robot_state_publisher-3] Link r_upper_arm had 1 children
[robot_state_publisher-3] Link r_lower_arm had 1 children
[robot_state_publisher-3] Link r_wrist had 0 children
[robot_state_publisher-3] Link imu_frame had 0 children
```

2022-06-17 20:43 UTC, clalancette commented
> The proposed changes seem to make sense. As @yuraSomatic did not further responde, could you (@clalancette) just do these changes and merge the PR?

There's a practical problem with doing that, in that I don't have permissions to push to @yuraSomatic's branch.  But I can open a new PR that has these changes.

That said, by default this is still going to print out those messages to the console.  The good news, though, is that you'll have more options to control what is being printed.

2022-06-17 20:43 UTC, closed without merging